/**
 * Auto-discovery codegen.
 *
 * Scans content/protocols/<protocol>/meta.ts and
 * content/protocols/<protocol>/flows/<flow>/{steps.ts,content.mdx} and emits
 * two generated files with STATIC imports (bundler-friendly):
 *
 *   content/registry.generated.ts   – pure data (meta + flow step definitions)
 *   content/content.generated.ts    – map of "<protocol>/<flow>" -> MDX component
 *
 * Run automatically via the pre* npm hooks (predev, prebuild, pretypecheck,
 * prevalidate-content). A new flow is picked up just by existing on disk — no
 * central list to edit. This is the key enabler for autonomous flow authoring.
 */
import { readdirSync, existsSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const PROTOCOLS_DIR = join(ROOT, "content", "protocols");

const ident = (s: string) => s.replace(/[^a-zA-Z0-9]/g, "_");

function dirs(p: string): string[] {
  if (!existsSync(p)) return [];
  return readdirSync(p).filter(
    (name) => !name.startsWith("_") && statSync(join(p, name)).isDirectory(),
  );
}

interface FlowEntry {
  protocol: string;
  flow: string;
  stepsImport: string; // ident
  hasContent: boolean;
  contentImport: string; // ident
}

const metaImports: string[] = [];
const protocolNames: string[] = [];
const flowEntries: FlowEntry[] = [];

for (const protocol of dirs(PROTOCOLS_DIR).sort()) {
  const protoDir = join(PROTOCOLS_DIR, protocol);
  const metaPath = join(protoDir, "meta.ts");
  if (!existsSync(metaPath)) {
    console.warn(`[build-registry] skipping ${protocol}: no meta.ts`);
    continue;
  }
  protocolNames.push(protocol);
  metaImports.push(
    `import meta_${ident(protocol)} from "./protocols/${protocol}/meta";`,
  );

  const flowsDir = join(protoDir, "flows");
  for (const flow of dirs(flowsDir).sort()) {
    const stepsPath = join(flowsDir, flow, "steps.ts");
    if (!existsSync(stepsPath)) {
      console.warn(
        `[build-registry] skipping ${protocol}/${flow}: no steps.ts`,
      );
      continue;
    }
    const hasContent = existsSync(join(flowsDir, flow, "content.mdx"));
    flowEntries.push({
      protocol,
      flow,
      stepsImport: `flow_${ident(protocol)}_${ident(flow)}`,
      hasContent,
      contentImport: `content_${ident(protocol)}_${ident(flow)}`,
    });
  }
}

// ---- content/registry.generated.ts (data only) ----------------------------
const dataLines: string[] = [
  "// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.",
  "// Run `npm run registry` to regenerate.",
  'import type { Flow, ProtocolMeta } from "@/lib/types";',
  ...metaImports,
  ...flowEntries.map(
    (e) =>
      `import ${e.stepsImport} from "./protocols/${e.protocol}/flows/${e.flow}/steps";`,
  ),
  "",
  "export interface RawProtocol { meta: ProtocolMeta; flows: Flow[]; }",
  "",
  "export const rawProtocols: RawProtocol[] = [",
  ...protocolNames.map((p) => {
    const flows = flowEntries
      .filter((e) => e.protocol === p)
      .map((e) => e.stepsImport)
      .join(", ");
    return `  { meta: meta_${ident(p)}, flows: [${flows}] },`;
  }),
  "];",
  "",
];

// ---- content/content.generated.ts (MDX component map) ----------------------
const withContent = flowEntries.filter((e) => e.hasContent);
const contentLines: string[] = [
  "// AUTO-GENERATED by scripts/build-registry.ts — do not edit by hand.",
  'import type { ComponentType } from "react";',
  ...withContent.map(
    (e) =>
      `import ${e.contentImport} from "./protocols/${e.protocol}/flows/${e.flow}/content.mdx";`,
  ),
  "",
  "export const flowContent: Record<string, ComponentType> = {",
  ...withContent.map(
    (e) => `  "${e.protocol}/${e.flow}": ${e.contentImport},`,
  ),
  "};",
  "",
];

const regOut = join(ROOT, "content", "registry.generated.ts");
const contentOut = join(ROOT, "content", "content.generated.ts");
writeFileSync(regOut, dataLines.join("\n"));
writeFileSync(contentOut, contentLines.join("\n"));

console.log(
  `[build-registry] ${protocolNames.length} protocol(s), ${flowEntries.length} flow(s) -> ${relative(ROOT, regOut)}, ${relative(ROOT, contentOut)}`,
);
